---
- hosts: build_host
  gather_facts: false
  tasks:
    - name: Include container build task for each container.
      include_tasks: "tasks/build.yml"
      with_items:
        - "vars/memoryleak-elasticsearch-7.6.2.yml"
        - "vars/memoryleak-nginx-alpine.yml"
        - "vars/memoryleak-base-alpine-3.12.yml"
        - "vars/memoryleak-php-7.3.yml"
        - "vars/memoryleak-php-7.3-xdebug.yml"
        - "vars/memoryleak-php-7.3-composer.yml"
        - "vars/memoryleak-php-7.4.yml"
        - "vars/memoryleak-php-7.4-xdebug.yml"
        - "vars/memoryleak-php-7.4-composer.yml"
      loop_control:
        loop_var: "container_config"
