---
container:
  namespace: memoryleak
  image: php
  version: 7.4-composer
  base: memoryleak/php:7.4
  run:
    - "apk add --no-cache git curl patch unzip php7-phar"
    - "curl -so /usr/local/bin/composer https://getcomposer.org/composer-2.phar"
    - "chmod +x /usr/local/bin/composer"
  files: []
  cmd: '["composer"]'
